-- 코드를 작성해주세요
SELECT MST.ID, SUB.FISH_NAME, MST.LENGTH
FROM FISH_INFO MST
JOIN(
    SELECT FI.FISH_TYPE AS FISH_TYPE
         , FN.FISH_NAME AS FISH_NAME
         , MAX(FI.LENGTH) AS LENGTH
      FROM FISH_INFO FI
      JOIN FISH_NAME_INFO FN
        ON FI.FISH_TYPE = FN.FISH_TYPE
     GROUP BY FI.FISH_TYPE, FN.FISH_NAME
        ) SUB
    ON MST.FISH_TYPE = SUB.FISH_TYPE
    AND MST.LENGTH = SUB.LENGTH
    ORDER BY MST.ID ASC